
modLoader="javafml"
loaderVersion="[43,)"
license="Apache-2.0"
[[mods]]
modId="betterbridging"
version="1.0.1"
displayName="Better Bridging"
updateJSONURL="https://infernalstudios.org/api/mods/betterbridging/forge"
logoFile="logo.png"
authors="Infernal Studios"
description='''Better Bridging adds the Bridge Brace, an item which allows you to place a column of mulitple blocks in one go when held in your off-hand.

Credits:
tinytransfem - Developer
Nekomaster1000 - Conceptualiser, Artist'''
[[dependencies.betterbridging]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.betterbridging]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"