
modLoader="javafml"
loaderVersion="[46,)"
license="Apache-2.0"
[[mods]]
modId="betterbridging"
version="1.0.0"
displayName="Better Bridging"
updateJSONURL="https://infernalstudios.org/api/mods/betterbridging/forge"
logoFile="logo.png"
authors="Infernal Studios"
description=""
[[dependencies.betterbridging]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.betterbridging]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"